// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfessionDriverApp.Infrastructure;

#nullable disable

namespace ProfessionDriverApp.Infrastructure.Migrations
{
    [DbContext(typeof(ProfessionDriverProjectContext))]
    partial class ProfessionDriverProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.DriverWorkLog", b =>
                {
                    b.Property<Guid>("DriverWorkLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<Guid?>("EndEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LargeGoodsVehicleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StartEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DriverWorkLogId");

                    b.HasIndex("DriverId");

                    b.HasIndex("EndEntryId");

                    b.HasIndex("LargeGoodsVehicleId");

                    b.HasIndex("StartEntryId");

                    b.ToTable("DriverWorkLogs");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.DriverWorkLogEntry", b =>
                {
                    b.Property<Guid>("DriverWorkLogEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Mileage")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("DriverWorkLogEntryId");

                    b.HasIndex("DriverId");

                    b.ToTable("DriverWorkLogEntries");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EntityId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.Individual", b =>
                {
                    b.Property<int>("IndividualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndividualId"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndividualName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IndividualId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.InsurancePolicy", b =>
                {
                    b.Property<int>("InsurancePolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsurancePolicyId"));

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsurancePolicyId");

                    b.ToTable("InsurancePolicies");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.LargeGoodsVehicle", b =>
                {
                    b.Property<int>("LargeGoodsVehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LargeGoodsVehicleId"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("TachoExpiryDate")
                        .HasColumnType("date");

                    b.Property<int?>("TrailerId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("LargeGoodsVehicleId");

                    b.HasIndex("TrailerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("LargeGoodsVehicles");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int?>("VehicleInspectionId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleInsuranceId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("EntityId");

                    b.HasIndex("VehicleInspectionId")
                        .IsUnique()
                        .HasFilter("[VehicleInspectionId] IS NOT NULL");

                    b.HasIndex("VehicleInsuranceId")
                        .IsUnique()
                        .HasFilter("[VehicleInsuranceId] IS NOT NULL");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.VehicleInspection", b =>
                {
                    b.Property<int>("VehicleInspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleInspectionId"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("VehicleInspectionId");

                    b.ToTable("VehicleInspections");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.VehicleInsurance", b =>
                {
                    b.Property<int>("VehicleInsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleInsuranceId"));

                    b.Property<int?>("AC_PolicyInsurancePolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OC_PolicyInsurancePolicyId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("VehicleInsuranceId");

                    b.HasIndex("AC_PolicyInsurancePolicyId");

                    b.HasIndex("OC_PolicyInsurancePolicyId");

                    b.ToTable("VehicleInsurances");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.Driver", b =>
                {
                    b.HasOne("ProfessionDriverApp.Domain.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.DriverWorkLog", b =>
                {
                    b.HasOne("ProfessionDriverApp.Domain.Models.Driver", "Driver")
                        .WithMany("DriverWorkLogs")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProfessionDriverApp.Domain.Models.DriverWorkLogEntry", "EndEntry")
                        .WithMany()
                        .HasForeignKey("EndEntryId");

                    b.HasOne("ProfessionDriverApp.Domain.Models.LargeGoodsVehicle", "LargeGoodsVehicle")
                        .WithMany("DriverWorkLogs")
                        .HasForeignKey("LargeGoodsVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfessionDriverApp.Domain.Models.DriverWorkLogEntry", "StartEntry")
                        .WithMany()
                        .HasForeignKey("StartEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("EndEntry");

                    b.Navigation("LargeGoodsVehicle");

                    b.Navigation("StartEntry");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.DriverWorkLogEntry", b =>
                {
                    b.HasOne("ProfessionDriverApp.Domain.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.Employee", b =>
                {
                    b.HasOne("ProfessionDriverApp.Domain.Models.Individual", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.LargeGoodsVehicle", b =>
                {
                    b.HasOne("ProfessionDriverApp.Domain.Models.Vehicle", "Trailer")
                        .WithMany()
                        .HasForeignKey("TrailerId");

                    b.HasOne("ProfessionDriverApp.Domain.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trailer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.Vehicle", b =>
                {
                    b.HasOne("ProfessionDriverApp.Domain.Models.Individual", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId");

                    b.HasOne("ProfessionDriverApp.Domain.Models.VehicleInspection", "VehicleInspection")
                        .WithOne("Vehicle")
                        .HasForeignKey("ProfessionDriverApp.Domain.Models.Vehicle", "VehicleInspectionId");

                    b.HasOne("ProfessionDriverApp.Domain.Models.VehicleInsurance", "VehicleInsurance")
                        .WithOne("Vehicle")
                        .HasForeignKey("ProfessionDriverApp.Domain.Models.Vehicle", "VehicleInsuranceId");

                    b.Navigation("Entity");

                    b.Navigation("VehicleInspection");

                    b.Navigation("VehicleInsurance");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.VehicleInsurance", b =>
                {
                    b.HasOne("ProfessionDriverApp.Domain.Models.InsurancePolicy", "AC_Policy")
                        .WithMany()
                        .HasForeignKey("AC_PolicyInsurancePolicyId");

                    b.HasOne("ProfessionDriverApp.Domain.Models.InsurancePolicy", "OC_Policy")
                        .WithMany()
                        .HasForeignKey("OC_PolicyInsurancePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AC_Policy");

                    b.Navigation("OC_Policy");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.Driver", b =>
                {
                    b.Navigation("DriverWorkLogs");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.LargeGoodsVehicle", b =>
                {
                    b.Navigation("DriverWorkLogs");
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.VehicleInspection", b =>
                {
                    b.Navigation("Vehicle")
                        .IsRequired();
                });

            modelBuilder.Entity("ProfessionDriverApp.Domain.Models.VehicleInsurance", b =>
                {
                    b.Navigation("Vehicle")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
